"""rename department

Revision ID: 33ca1aee3b7b
Revises: 51a84e8ce885
Create Date: 2025-06-10 18:15:30.722269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ca1aee3b7b'
down_revision = '51a84e8ce885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
